<template>
  <div class="form-container">
    <el-steps :active="status" finish-status="success" simple style="marginBottom: 20px;">
      <el-step title="步骤 1"></el-step>
      <el-step title="步骤 2"></el-step>
      <el-step title="步骤 3"></el-step>
      <el-step title="步骤 4"></el-step>
    </el-steps>
    <!-- 返回上一步 -->
    <!-- <el-button v-if="canGoBack" @click="goBack">返回上一步</el-button> -->
    <!-- 动态渲染当前状态组件 -->
    <component :is="statusCom" @onChangeStatus="changeStatus" />
  </div>
</template>
<script>
import step1 from './status-components/step1'
import step2 from './status-components/step2'
import step3 from './status-components/step3'
import step4 from './status-components/step4'
const DEFAULT_STATUS = 1
export default {
  name: 'status-form',
  components: {
    step1,
    step2,
    step3,
    step4
  },
  computed: {
    statusCom: function () {
      const statusMap = {
        1: step1,
        2: step2,
        3: step3,
        4: step4
      }
      return statusMap[this.status]
    },
    canGoBack: function () {
      return this.cache.length > 0
    }
  },
  data () {
    return {
      status: DEFAULT_STATUS
    }
  },
  methods: {
    createDom () {
    },
    changeStatus (val) {
      this.cache.push(val)
      this.status = val
    },
    goBack () {
      // 弹出当前状态
      this.cache.pop()
      // 改变状态为上一个状态
      this.status = this.cache[this.cache.length - 1] || DEFAULT_STATUS
    }
  },
  created () {
    let data = {
      "RECORDS": [
        {
          "ID": "source.schema00000000000001",
          "VERSION": "0",
          "NAME": "schema",
          "CODE": "source.schema",
          "VALUE": "default",
          "VALUETEXT": "默认",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "source.schema00000000000002",
          "VERSION": "0",
          "NAME": "schema",
          "CODE": "source.schema",
          "VALUE": "all",
          "VALUETEXT": "全部",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "source.schema00000000000003",
          "VERSION": "0",
          "NAME": "schema",
          "CODE": "source.schema",
          "VALUE": "custom",
          "VALUETEXT": "自定义",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceBaseType0000000000001",
          "VERSION": "0",
          "NAME": "数据源类型[文件、数据库]",
          "CODE": "source.baseType",
          "VALUE": "DB",
          "VALUETEXT": "数据源",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceBaseType0000000000002",
          "VERSION": "0",
          "NAME": "数据源类型[文件、数据库]",
          "CODE": "source.baseType",
          "VALUE": "FILE",
          "VALUETEXT": "文件源",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceCharset000000000000001",
          "VERSION": "0",
          "NAME": "字符集",
          "CODE": "source.charset",
          "VALUE": "UTF-8",
          "VALUETEXT": "UTF-8",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceCharset000000000000002",
          "VERSION": "0",
          "NAME": "字符集",
          "CODE": "source.charset",
          "VALUE": "IS08859-1",
          "VALUETEXT": "IS08859-1",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceCharset000000000000003",
          "VERSION": "0",
          "NAME": "字符集",
          "CODE": "source.charset",
          "VALUE": "GBK",
          "VALUETEXT": "GBK",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceCharset000000000000004",
          "VERSION": "0",
          "NAME": "字符集",
          "CODE": "source.charset",
          "VALUE": "GB2312",
          "VALUETEXT": "GB2312",
          "SORTCODE": "4",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceSourceType0000000000001",
          "VERSION": "0",
          "NAME": "数据源类型",
          "CODE": "source.sourceType",
          "VALUE": "FTP",
          "VALUETEXT": "FTP服务器",
          "SORTCODE": "1",
          "PARENTID": "sourceBaseType0000000000002",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceSourceType0000000000002",
          "VERSION": "0",
          "NAME": "数据源类型",
          "CODE": "source.sourceType",
          "VALUE": "XFTP",
          "VALUETEXT": "XFTP服务器",
          "SORTCODE": "2",
          "PARENTID": "sourceBaseType0000000000002",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sourceSourceType000000000db01",
          "VERSION": "0",
          "NAME": "数据源类型",
          "CODE": "source.sourceType",
          "VALUE": "MYSQL",
          "VALUETEXT": "MYSQL服务器",
          "SORTCODE": "1",
          "PARENTID": "sourceBaseType0000000000001",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyCompareType0000000001",
          "VERSION": "0",
          "NAME": "比较方式",
          "CODE": "strategy.compareType",
          "VALUE": "GT",
          "VALUETEXT": "大于",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyCompareType0000000002",
          "VERSION": "0",
          "NAME": "比较方式",
          "CODE": "strategy.compareType",
          "VALUE": "LT",
          "VALUETEXT": "小于",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFieldType0000000000001",
          "VERSION": "0",
          "NAME": "数据类型",
          "CODE": "strategy.fieldType",
          "VALUE": "FILE",
          "VALUETEXT": "文件型",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFieldType0000000000002",
          "VERSION": "0",
          "NAME": "数据类型",
          "CODE": "strategy.fieldType",
          "VALUE": "INTEGER",
          "VALUETEXT": "整型",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFieldType0000000000003",
          "VERSION": "0",
          "NAME": "数据类型",
          "CODE": "strategy.fieldType",
          "VALUE": "FLOAT",
          "VALUETEXT": "浮点型",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFieldType0000000000004",
          "VERSION": "0",
          "NAME": "数据类型",
          "CODE": "strategy.fieldType",
          "VALUE": "TIMESTAMP",
          "VALUETEXT": "时间戳",
          "SORTCODE": "4",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFieldType0000000000005",
          "VERSION": "0",
          "NAME": "数据类型",
          "CODE": "strategy.fieldType",
          "VALUE": "DATE",
          "VALUETEXT": "日期型",
          "SORTCODE": "5",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000001",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "HTML",
          "VALUETEXT": "html",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000002",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "XML",
          "VALUETEXT": "xml",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000003",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "PDF",
          "VALUETEXT": "pdf",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000004",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "RAR",
          "VALUETEXT": "rar",
          "SORTCODE": "4",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000005",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "7Z",
          "VALUETEXT": "7z",
          "SORTCODE": "5",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000006",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "ZIP",
          "VALUETEXT": "zip",
          "SORTCODE": "6",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000007",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "TAR",
          "VALUETEXT": "tar",
          "SORTCODE": "7",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000008",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "TXT",
          "VALUETEXT": "txt",
          "SORTCODE": "8",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000009",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "WORD",
          "VALUETEXT": "word",
          "SORTCODE": "9",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000010",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "EXCEL",
          "VALUETEXT": "excel",
          "SORTCODE": "10",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000011",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "PPT",
          "VALUETEXT": "ppt",
          "SORTCODE": "11",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000012",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "MAG",
          "VALUETEXT": "mag",
          "SORTCODE": "12",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000013",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "VSD",
          "VALUETEXT": "vsd",
          "SORTCODE": "13",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyFileExtention00000000014",
          "VERSION": "0",
          "NAME": "文件类型",
          "CODE": "strategy.fileExtention",
          "VALUE": "MPP",
          "VALUETEXT": "mpp",
          "SORTCODE": "14",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyIsSystem0000000000001",
          "VERSION": "0",
          "NAME": "模板系统类型",
          "CODE": "strategy.isSystem",
          "VALUE": "DEFAULT",
          "VALUETEXT": "默认",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyIsSystem0000000000002",
          "VERSION": "0",
          "NAME": "模板系统类型",
          "CODE": "strategy.isSystem",
          "VALUE": "CUSTOM",
          "VALUETEXT": "自定义",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyMatchType0000000000001",
          "VERSION": "0",
          "NAME": "匹配方式",
          "CODE": "strategy.matchType",
          "VALUE": "CONTAIN",
          "VALUETEXT": "包含",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyMatchType0000000000002",
          "VERSION": "0",
          "NAME": "匹配方式",
          "CODE": "strategy.matchType",
          "VALUE": "EQUAL",
          "VALUETEXT": "等于",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyMatchType0000000000003",
          "VERSION": "0",
          "NAME": "匹配方式",
          "CODE": "strategy.matchType",
          "VALUE": "STARTWITH",
          "VALUETEXT": "以该文字开始",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyMatchType0000000000004",
          "VERSION": "0",
          "NAME": "匹配方式",
          "CODE": "strategy.matchType",
          "VALUE": "ENDWITH",
          "VALUETEXT": "以该文字结束",
          "SORTCODE": "4",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyMatchType0000000000005",
          "VERSION": "0",
          "NAME": "匹配方式",
          "CODE": "strategy.matchType",
          "VALUE": "REGEXP",
          "VALUETEXT": "正则表达式",
          "SORTCODE": "5",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyRiskLevel0000000000001",
          "VERSION": "0",
          "NAME": "严重程度",
          "CODE": "strategy.riskLevel",
          "VALUE": "high",
          "VALUETEXT": "高",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyRiskLevel0000000000002",
          "VERSION": "0",
          "NAME": "严重程度",
          "CODE": "strategy.riskLevel",
          "VALUE": "middle",
          "VALUETEXT": "中",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyRiskLevel0000000000003",
          "VERSION": "0",
          "NAME": "严重程度",
          "CODE": "strategy.riskLevel",
          "VALUE": "low",
          "VALUETEXT": "低",
          "SORTCODE": "3",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyStrategyType000000000001",
          "VERSION": "0",
          "NAME": "策略类型",
          "CODE": "strategy.strategyType",
          "VALUE": "DB",
          "VALUETEXT": "数据库策略",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "strategyStrategyType000000000002",
          "VERSION": "0",
          "NAME": "策略类型",
          "CODE": "strategy.strategyType",
          "VALUE": "FILE",
          "VALUETEXT": "文件策略",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sys.yesOrNo0000000000000001",
          "VERSION": "0",
          "NAME": "是否",
          "CODE": "sys.yesOrNo",
          "VALUE": "Y",
          "VALUETEXT": "是",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "sys.yesOrNo0000000000000002",
          "VERSION": "0",
          "NAME": "是否",
          "CODE": "sys.yesOrNo",
          "VALUE": "N",
          "VALUETEXT": "否",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.scanMethod000000000001",
          "VERSION": "0",
          "NAME": "扫描方式 ",
          "CODE": "task.scanMethod",
          "VALUE": "all",
          "VALUETEXT": "全表、文件扫描",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.scanMethod000000000002",
          "VERSION": "0",
          "NAME": "扫描方式 ",
          "CODE": "task.scanMethod",
          "VALUE": "demo",
          "VALUETEXT": "样本",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.scanType000000000000001",
          "VERSION": "0",
          "NAME": "扫描类型",
          "CODE": "task.scanType",
          "VALUE": "increment",
          "VALUETEXT": "增量",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.scanType000000000000002",
          "VERSION": "0",
          "NAME": "扫描类型",
          "CODE": "task.scanType",
          "VALUE": "fullDose",
          "VALUETEXT": "全量",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.startNow0000000000000001",
          "VERSION": "0",
          "NAME": "执行方式",
          "CODE": "task.startNow",
          "VALUE": "now",
          "VALUETEXT": "立即",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.startNow0000000000000002",
          "VERSION": "0",
          "NAME": "执行方式",
          "CODE": "task.startNow",
          "VALUE": "custom",
          "VALUETEXT": "自定义",
          "SORTCODE": "2",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000001",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "executory",
          "VALUETEXT": "执行中",
          "SORTCODE": "1",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000002",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "pause",
          "VALUETEXT": "暂停",
          "SORTCODE": "0",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000003",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "stop",
          "VALUETEXT": "停止",
          "SORTCODE": "0",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000004",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "complete",
          "VALUETEXT": "完成",
          "SORTCODE": "0",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000005",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "notBegin",
          "VALUETEXT": "未开始",
          "SORTCODE": "0",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        },
        {
          "ID": "task.status0000000000000000006",
          "VERSION": "0",
          "NAME": "任务执行状态",
          "CODE": "task.status",
          "VALUE": "abnormal",
          "VALUETEXT": "异常终止",
          "SORTCODE": "0",
          "PARENTID": "",
          "ISENABLED": "Y",
          "ISDEFAULT": "N",
          "ISSYSTEM": "N",
          "CREATEUSER": "",
          "CREATETIME": "",
          "UPDATEUSER": "",
          "UPDATETIME": ""
        }
      ]
    }

    let aa = data.RECORDS.reduce((prev, item) => {
      let key = item.CODE
      if (key in prev) {
        prev[key].push(
          {
            value: item.VALUE,
            valueText: item.VALUETEXT
          }
        )
        // if (value in prev[key]) {

        // } else {
        //   let arr = []
        //   arr.push({
        //     value: item.VALUE,
        //     valueText: item.VALUETEXT
        //   })
        //   prev[key][value] = arr
        // }
      } else {
        prev[key] = [
          {
            value: item.VALUE,
            valueText: item.VALUETEXT
          }
        ]
      }
      return prev
    }, {})
    console.log(JSON.stringify(aa))
  }
}
</script>
